export default function ArtigoInvestimentos() {
  return (
    <div className="max-w-3xl mx-auto mt-32 text-white">
                          <h1 className='text-[48px] font-[700] text-white leading-[70px]'>Porque expatriar meu capital com o Dólar em alta?</h1>
                          <p className='text-[20px] text-white leading-[36.04px] mt-[64px]'>
                              Sabidamente a maior e mais ativa economia do mundo, os Estados Unidos contam com cerca de 6000 empresas listadas nas bolsas NYSE (New York Stock Exchange) e NASDAQ (National Association of Securities Dealers Automated Quotations). Ambas localizadas em Nova York, sendo a primeira a que reúne as empresas dos setores mais tradicionais, como o de alimentos e bebidas, varejo, aviação e financeiro, e a segunda a que concentra empresas do segmento de tecnologia e inovação, como Google/Alphabet, Nvidia e Microsoft.
                              Apenas o grupo formado pelas maiores empresas de tecnologia do mundo, chamado de “sete magníficas”, com Alphabet, Nvidia, Microsoft, Amazon, Tesla, Meta e Apple soma um valor de mercado em 2024 mais de 3 vezes maior do que o PIB brasileiro. Sim, um punhado de empresas, entre as mais influentes do mundo, das quais praticamente todos nós somos usuários de algum de seus serviços, valem mais do que tudo o que o Brasil produz.
                              <br /><br />
                              E esses são apenas alguns exemplos da força representada pelo mercado americano, uma vez que outras gigantes como Coca-Cola, Pepsico, FedEx, General Motors, Johnson&Johnson e Oracle também tiveram origem nos Estados Unidos, impactam nossas vidas diariamente e têm suas ações negociadas na bolsa de Nova York.
                          </p>
                          <img className='mt-[48px]' src='/temp/10.jpeg' alt='money' />
                          <p className='text-[20px] text-white leading-[36.04px] mt-[48px]'>
                              Enquanto a instabilidade que reina no Brasil nos força a investir em renda fixa, como forma de proteção às mudanças impostas por governos e, mais recentemente, pelo judiciário, nos Estados Unidos o investidor médio tem condições ideais para o investimento nas empresas de capital aberto. O país conta com mais de 5000 empresas listadas em bolsa - em quantidade, isso é mais de 10 vezes o nosso mercado. Em volume de investimento, no entanto, a diferença é ainda maior: enquanto a B3 tem uma média de US$ 4 Bi diários, somadas, NYSE E NASDAQ chegam a cerca de US$ 60 Bi diários. E nem incluímos aqui a Bolsa de Chicago (CME Group), especializada em commodities. Um mercado com tamanho vigor oferece inúmeras oportunidades, com muito mais segurança do que o ambiente que encontramos no Brasil.
                              <br /><br />
                              Mas as oportunidades não se restringem a renda variável, da qual o investimento em ações / bolsa é a modalidade mais conhecida. Sim, as grandes oportunidades de ganho de capital em geral encontram-se no mercado de ações, especialmente na valorização de empresas. Um mercado menos regulado, mais aberto, regido por meritocracia e competência, oferece um maior potencial de ganhos. Nos últimos 15 anos o S&P500, principal índice de investimentos do mundo, que concentra os resultados das 500 maiores empresas americanas, tem crescido em média 10% ao ano - na moeda mais utilizada no mundo.
                              Ou seja, quem investe em um ETF atrelado a esse índice, ganhou, em dólar, 10% ao ano, mais a valorização da moeda frente ao Real.
                              <br /><br />
                              Ainda que esses dados sejam animadores, sabemos que investidores mais conservadores sentem-se desconfortáveis com a renda variável, por diversos motivos. Mas assim como no Brasil, os EUA contam com opções como fundos de investimento, ETFs, FIIs e títulos de renda fixa. Em muito maior volume e diversificação do que encontramos no nosso mercado. Por exemplo, podemos investir em um ETF de tecnologia, de semicondutores, de ouro, ou de diversos outros setores que no Brasil são inexistentes ou irrelevantes - com a vantagem de contar com a análise e gestão de profissionais altamente capacitados, que conhecem a fundo o mercado e as empresas investidas. Na renda fixa encontramos desde os títulos mais seguros do mundo, emitidos pelo governo americano, até os de empresas privadas como a Amazon.
                              <br /><br />
                              Mas afinal, devemos investir nos Estados Unidos como oportunidade ou estratégia? Bem, em um mercado com as condições descritas, com tamanha potência, ambas as modalidades são válidas e devem ser mantidas. Investir nos Estados Unidos é e sempre será estratégico, do ponto de vista de que se trata de uma diversificação necessária em nossa carteira, para proteger nosso patrimônio e participar de mercados que não temos representados por aqui; ao mesmo tempo trata-se de uma oportunidade de potencializar ganhos em momentos específicos, sejam de curto prazo e focados em um segmento ou companhia específico, seja por um momento de mercado.
                              <br /><br />
                              Não podemos finalizar sem dizer, no entanto, que uma orientação profissional qualificada é essencial na decisão de investimentos, pois mesmo os investimentos mais conservadores e seguros poderão oferecer riscos se determinados fatores não forem considerados.
                          </p>
                          <h2 className='text-[32px] font-[600] text-white leading-[50px] mt-[64px]'>Warren Buffett: o exemplo de paciência e estratégia</h2>
                          <p className='text-[20px] text-white leading-[36.04px] mt-[32px]'>
                              Warren Buffett, provavelmente o maior investidor de todos os tempos, mantém-se como uma pessoa extremamente conservadora em seus hábitos. Simples, pacato, avesso a holofotes, anda em um Cadillac dos anos 2000, não usa ternos ou relógios caros, mora na mesma casa em uma cidade pequena do interior americano, come hambúrgueres com Coca-Cola todos os dias e não costuma ser visto em eventos de figurões. Dedica-se a administrar com cuidado seus investimentos, em geral feitos nas empresas de grande faturamento e que atuam em mercados consolidados.
                              <br /><br />
                              Um dos fatores de seu sucesso é o conhecimento profundo das bases de cada empresa investida: sua saúde financeira, a cultura empresarial, a qualidade da gestão, o que a gestão pensa sobre o futuro da companhia e as projeções de vendas e os planos de investimento. Avalia profundamente o mercado em que atua, a posição da empresa, sua reputação e a percepção do consumidor. Analisa todas as variáveis que podem impactar no negócio e nos resultados da empresa.
                              <br /><br />
                              Outro é a paciência, que anda junto com o tempo. Muito da expressiva rentabilidade que seus investimentos obtêm, vêm após uma longa maturação: os fundamentos, que são a base de seus resultados, quando bem geridos tornam-se consistentes e sustentáveis, mas necessitam de tempo. Consistência, coerência, persistência, planejamento e estratégia. Warren Buffett não especula, não espera ganhos de curto prazo e tem a paciência que a quase totalidade dos investidores não têm - o que o torna altamente diferenciado e o levou à posição que ocupa há décadas.
                          </p>
                          <h2 className='text-[32px] font-[600] text-white leading-[50px] mt-[64px]'>Por que dolarizar o patrimônio?</h2>
                          <p className='text-[20px] text-white leading-[36.04px] mt-[32px]'>
                              Da mesma forma devemos proceder com o Dólar. Moeda mais forte do mundo, utilizada tanto entre países e instituições financeiras mundiais na definição de suas dívidas, receitas e resultados, o Dólar é a moeda mais líquida do mundo, a mais conhecida e desejada, que em muitos países pode ser tão ou mais aceita do que a moeda local.
                              <br /><br />
                              Seja por governos, empresas privadas ou cidadãos, o mundo aceita Dólares na operação de transações comerciais ou na valoração destas. O Dólar literalmente define o curso do comércio mundial, o custo de commodities, a dívida ou reserva de governos e empresas e a riqueza de pessoas de todo o mundo. Bancos da Suíça, Argentina, Uruguai, e praticamente todos os países do mundo guardam o patrimônio de clientes em Dólar.
                              <br /><br />
                              Obter e manter Dólares em nosso poder há muitas décadas representa proteção cambial, reserva de emergência, valorização patrimonial e segurança em momentos de crise. Investidores do mundo inteiro recorrem à compra de Dólares em momentos de crise.
                              <br /><br />
                              Mas como qualquer moeda de livre negociação, o Dólar sofre variações em seu valor frente a outros benchmarks e moedas. Decisões político-econômicas, acontecimentos geopolíticos, catástrofes naturais e outras ocorrências de grande magnitude podem interferir na valorização do Dólar. Sentimos isso em nosso Real, que sofre os efeitos de decisões do governo referentes à economia, política e legislação. Após ter permanecido em torno dos R$ 5,00 em grande parte de 2023 e 2024, a cotação do Dólar subiu para algo próximo de R$ 5,70, em virtude da situação fiscal do país, que se deteriora a cada dia.
                              <br /><br />
                              Por que, então, dolarizar o patrimônio em um período de alta? Porque assim como Warren Buffett, devemos investir em Dólar de forma estratégica, com consistência, paciência e coerência. Desde sua criação, há 30 anos, o Real perdeu cerca de 84% de seu valor; no mesmo período, o Dólar desvalorizou-se em 35%. Historicamente, os períodos de alta da moeda americana são muito mais duradouros e resistentes; quando há uma reversão, esta será sucedida por novo período de alta, alcançando um novo patamar de valorização. Ou seja, ainda que aparentemente caro, não apenas mantém seu poder de compra por muito mais tempo do que o Real, como tende a manter-se em uma constante valorização frente à nossa moeda.
                              <br /><br />
                              Assim como Warren Buffett faz com seus investimentos, devemos tratar o Dólar com estratégia, consistência, coerência e paciência. Uma famosa frase, que deve sempre ser lembrada, diz que ‘Dólar caro é o Dólar que não se tem’. Em uma livre adaptação de outra, igualmente famosa e de autoria do Sr. Buffett, podemos dizer: never bet against Dólar.
                          </p>
    </div>
  )
}
