export default function ArtigoInvestimentos() {
  return (
    <div className="max-w-3xl mx-auto mt-32 text-white">
                                <h1 className='text-[48px] font-[700] text-white leading-[70px]'>
                              A crise de 2008: um divisor de água
                          </h1>
                          <p className='text-[20px] text-white leading-[36.04px] mt-[64px]'>
                              Nos acostumamos a ter a Europa no centro de nossas atenções, por diversos motivos: berço da civilização do Ocidente, da industrialização, continente com o maior número de países, culturas, idiomas, de onde uma expressiva parcela da população brasileira tem origens.
                              Um grupo de nações que ao longo de centenas de anos desenvolveu sistemas de governo, fortaleceu seus sistemas e viu suas sociedades evoluírem de uma forma mais igualitária, sem os grandes desequilíbrios sociais que temos em países do terceiro mundo e emergentes como o Brasil.
                              <br />
                              <br />
                              Há três décadas, o bloco das economias mais desenvolvidas da Europa decidiu unificar-se com a criação do Euro, que foi adotado como moeda comum na maioria do bloco. A força econômica desse grupo, associada a outros fatores como sua capacidade industrial, seu foco em itens de alto valor agregado, o nível educacional e a qualificação média de sua população e o potencial de consumo do bloco mantiveram o Euro em um nível sempre muito próximo ao Dólar, algo semelhante entre as nações que optaram por não adotar o Euro, como o Reino Unido e a Suíça.
                              Em 2008, a crise do “sub-prime”, causada pelo excesso de exposição de instituições financeiras no financiamento imobiliário de baixa qualificação/alto risco, gerou uma queda vertiginosa de crédito em todo o mundo, com um período inicial recessivo, seguido de uma lenta recuperação dos mercados em todo o mundo. Os Estados Unidos, onde se originou essa trágica situação, que incluiu quebra de bancos e de empresas, foi o país mais atingido. Com forte bloco econômico, uma rígida regulação imposta a seus integrantes e uma dependência relativamente baixa dos Estados Unidos, a Europa viria a sofrer muito menos e viria a ter uma recuperação mais rápida. Até então, tudo dentro do esperado.
                              Mas o que se viu em um segundo momento foi um crescimento vigoroso da economia americana, que teve sua renda per capita praticamente dobrada desde então, com uma taxa de crescimento descolada da que se observou na Europa. No mesmo período, na chamada Zona do Euro a renda per capita se manteve em um nível muito próximo ao anterior.
                              <br />
                              <br />
                              Sob outro ângulo, o Reino Unido, que deixou a Comunidade Econômica Européia em busca de maior flexibilidade em negociações e maior crescimento econômico, hoje tem sua renda média inferior ao estado do Mississippi, a menor economia entre os estados americanos.
                              Em um terceiro ponto de vista: há cerca de 20 anos, quatro das dez maiores empresas do mundo era americanas, quatro européias e duas japonesas. Atualmente, nove das dez maiores são dos Estados Unidos e uma da Arábia Saudita. Apple, Microsoft e Nvidia, separadamente, hoje valem mais do que o total das empresas com ações comercializadas na Bolsa de Frankfurt (FSE), uma das maiores e mais importantes do mundo.
                              Assim como ocorreu em todo o mundo, a crise gerada pela pandemia afetou economicamente os Estados Unidos, que sofreram especialmente com a alta da inflação pelos estímulos lançados a diversos setores e também aos trabalhadores, buscando compensar os efeitos negativos de ações como o lockdown. Mesmo convivendo até hoje com juros em um patamar elevado e incomum para o país, a economia seguiu crescendo e mantém-se vigorosa. Com a definição das eleições e a composição da nova equipe de governo, o cenário indica a possibilidade de uma nova era de forte crescimento dos Estados Unidos, com desregulamentação e queda de impostos.
                              <br />
                              <br />
                              Ainda tratando de ambiente interno: em termos populacionais, o país será o único do ocidente que manterá sua população em crescimento nos próximos 25 anos. Enquanto Brasil, Argentina, toda a Zona do Euro vêm suas populações economicamente ativas em declínio, impondo mais peso ao estado e limitando sua capacidade de investimento e geração de renda, os Estados Unidos seguem com taxas de natalidade x mortalidade positivas e fluxos migratórios importantes que os mantêm em forte crescimento.
                              A história recente nos mostra fatos que corroboram a força da economia americana e confirmam que as condições de mercado necessárias para que ela siga vigorosa continuam presentes. Um mercado com pouca regulamentação, uma cultura baseada em performance e meritocracia e um cenário positivo sendo desenhado.
                              Todo esse conjunto reforça a tese de investimentos nos Estados Unidos como destino preferencial de investimentos estrangeiros para acúmulo de capital e proteção patrimonial.
                          </p>
                          <img className='mt-[48px]' src='/temp/9.jpeg' alt='money' />
                          <p className='text-[20px] text-white leading-[36.04px] mt-[48px]'>
                              Sabidamente a maior e mais ativa economia do mundo, os Estados Unidos contam com cerca de 6000 empresas listadas nas bolsas NYSE (New York Stock Exchange) e NASDAQ (National Association of Securities Dealers Automated Quotations). Ambas localizadas em Nova York, sendo a primeira a que reúne as empresas dos setores mais tradicionais, como o de alimentos e bebidas, varejo, aviação e financeiro, e a segunda a que concentra empresas do segmento de tecnologia e inovação, como Google/Alphabet, Nvidia e Microsoft.
                              Apenas o grupo formado pelas maiores empresas de tecnologia do mundo, chamado de “sete magníficas”, com Alphabet, Nvidia, Microsoft, Amazon, Tesla, Meta e Apple soma um valor de mercado em 2024 mais de 3 vezes maior do que o PIB brasileiro. Sim, um punhado de empresas, entre as mais influentes do mundo, das quais praticamente todos nós somos usuários de algum de seus serviços, valem mais do que tudo o que o Brasil produz.
                              E esses são apenas alguns exemplos da força representada pelo mercado americano, uma vez que outras gigantes como Coca-Cola, Pepsico, FedEx, General Motors, Johnson&Johnson e Oracle também tiveram origem nos Estados Unidos, impactam nossas vidas diariamente e têm suas ações negociadas na bolsa de Nova York.
                          </p>
                          <p className='text-[20px] text-white leading-[36.04px] mt-[48px]'>
                              Enquanto a instabilidade que reina no Brasil nos força a investir em renda fixa, como forma de proteção às mudanças impostas por governos e, mais recentemente, pelo judiciário, nos Estados Unidos o investidor médio tem condições ideais para o investimento nas empresas de capital aberto. O país conta com mais de 5000 empresas listadas em bolsa - em quantidade, isso é mais de 10 vezes o nosso mercado. Em volume de investimento, no entanto, a diferença é ainda maior: enquanto a B3 tem uma média de US$ 4 Bi diários, somadas, NYSE E NASDAQ chegam a cerca de US$ 60 Bi diários. E nem incluímos aqui a Bolsa de Chicago (CME Group), especializada em commodities. Um mercado com tamanho vigor oferece inúmeras oportunidades, com muito mais segurança do que o ambiente que encontramos no Brasil.
                              <br />
                              <br />
                              Mas as oportunidades não se restringem a renda variável, da qual o investimento em ações / bolsa é a modalidade mais conhecida. Sim, as grandes oportunidades de ganho de capital em geral encontram-se no mercado de ações, especialmente na valorização de empresas. Um mercado menos regulado, mais aberto, regido por meritocracia e competência, oferece um maior potencial de ganhos. Nos últimos 15 anos o S&P500, principal índice de investimentos do mundo, que concentra os resultados das 500 maiores empresas americanas, tem crescido em média 10% ao ano - na moeda mais utilizada no mundo.
                              <br />
                              <br />
                              Ou seja, quem investe em um ETF atrelado a esse índice, ganhou, em dólar, 10% ao ano, mais a valorização da moeda frente ao Real.
                              <br />
                              <br />
                              Ainda que esses dados sejam animadores, sabemos que investidores mais conservadores sentem-se desconfortáveis com a renda variável, por diversos motivos. Mas assim como no Brasil, os EUA contam com opções como fundos de investimento, ETFs, FIIs e títulos de renda fixa. Em muito maior volume e diversificação do que encontramos no nosso mercado. Por exemplo, podemos investir em um ETF de tecnologia, de semicondutores, de ouro, ou de diversos outros setores que no Brasil são inexistentes ou irrelevantes - com a vantagem de contar com a análise e gestão de profissionais altamente capacitados, que conhecem a fundo o mercado e as empresas investidas. Na renda fixa encontramos desde os títulos mais seguros do mundo, emitidos pelo governo americano, até os de empresas privadas como a Amazon.
                              <br />
                              <br />
                              Mas afinal, devemos investir nos Estados Unidos como oportunidade ou estratégia? Bem, em um mercado com as condições descritas, com tamanha potência, ambas as modalidades são válidas e devem ser mantidas. Investir nos Estados Unidos é e sempre será estratégico, do ponto de vista de que se trata de uma diversificação necessária em nossa carteira, para proteger nosso patrimônio e participar de mercados que não temos representados por aqui; ao mesmo tempo trata-se de uma oportunidade de potencializar ganhos em momentos específicos, sejam de curto prazo e focados em um segmento ou companhia específico, seja por um momento de mercado.
                              <br />
                              <br />
                              Não podemos finalizar sem dizer, no entanto, que uma orientação profissional qualificada é essencial na decisão de investimentos, pois mesmo os investimentos mais conservadores e seguros poderão oferecer riscos se determinados fatores não forem considerados.
                          </p>
    </div>
  )
}
